#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

# Starship Config
export STARSHIP_CONFIG=$XDG_CONFIG_HOME/starship/starship.toml

# PATH User
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/bin":$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.miniconda/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go

# Man Config
export MANPAGER='vim +Man!'
export MANWIDTH=999


# eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
